act: sin
device: cuda
epoch: 1
icbc_w: 5000.0
max_iter: 50000
n_coll: 1048576
n_int: 0
n_nn_lay: 8
n_nn_neu: 32
n_u: 524288
n_valid: 0
optim: LBFGS
point_type: moving_center
reg_exp: 2
reg_w: 0.0
restart_folder: ''
retrain_seed: 32
sampling_seed: 128
shuffle_set: false
verbose_set: false